# Generated by Django 6.0.3 on 2026-05-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finishing_v2', '0003_finishingjob_order_stage'),
        ('production_v2', '0016_alter_finishedblock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingjob',
            name='input_finished_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_jobs', to='production_v2.finishedblock'),
        ),
    ]
