# Generated by Django 6.0.3 on 2026-05-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('REFERRAL', 'Tavsiya'), ('WEBSITE', 'Veb-sayt'), ('COLD_CALL', "Sovuq qo'ng'iroq"), ('EXHIBITION', "Ko'rgazma"), ('SOCIAL', 'Ijtimoiy tarmoq'), ('OTHER', 'Boshqa')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('CONTACTED', "Bog'lanildi"), ('NEGOTIATION', 'Muzokara'), ('WON', 'Yutildi'), ('LOST', 'Yutqazildi')], default='NEW', max_length=15)),
                ('amount_expected', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', "Qo'ng'iroq"), ('EMAIL', 'Email'), ('MEETING', 'Uchrashuv'), ('NOTE', 'Izoh')], default='NOTE', max_length=10)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
