# Generated by Django 6.0.3 on 2026-05-11 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0012_alter_batchreservation_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousetransfer',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='transfers/attachments/'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse_v2.rawmaterialbatch'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Past'), ('NORMAL', 'O‘rtacha'), ('HIGH', 'Yuqori'), ('URGENT', 'SHOSHILINCH')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='reason',
            field=models.TextField(blank=True, help_text="O'tkazma sababi"),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_shipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='transfer_type',
            field=models.CharField(choices=[('PRODUCTION', 'Ishlab chiqarish uchun'), ('WAREHOUSE', 'Omborlararo'), ('QC', 'Sifat nazorati (QC)'), ('RETURN', 'Qaytarish'), ('WASTE', 'Brak / Chiqindi')], default='WAREHOUSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Tasdiqlash kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('SHIPPED', 'Yo‘lda (Jo‘natildi)'), ('RECEIVED', 'Qabul qilindi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20),
        ),
    ]
