# Generated by Django 6.0.3 on 2026-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_v2', '0015_warehousetransfer_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Tasdiqlash kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('IN_TRANSIT', 'Yo‘lda'), ('SHIPPED', 'Yo‘lda (Eski holat)'), ('RECEIVED', 'Qabul qilindi'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20),
        ),
    ]
