# Generated by Django 6.0.3 on 2026-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(blank=True, help_text='Product name or ALL', max_length=255)),
                ('condition_type', models.CharField(choices=[('QUANTITY', "Miqdor bo'yicha"), ('CUSTOMER_TYPE', "Mijoz turi bo'yicha"), ('SEASON', "Mavsum bo'yicha"), ('REGION', "Hudud bo'yicha"), ('LOYALTY', "Sodiqlik bo'yicha")], default='QUANTITY', max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, help_text='Min quantity or other threshold value', max_digits=12)),
                ('adjustment_type', models.CharField(choices=[('PERCENT', 'Foiz'), ('FIXED', "Qat'iy miqdor")], default='PERCENT', max_length=10)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0, help_text='Discount/markup value', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
