# Generated by Django 6.0.3 on 2026-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_assigned_warehouses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('PENDING', 'Pending'), ('RESIGNED', 'Resigned'), ('VACATION', 'Vacation')], default='ACTIVE', max_length=20),
        ),
    ]
