# Generated by Django 6.0.3 on 2026-05-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorybatch_inventorymovement_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorybatch',),
        ),
    ]
