# Generated by Django 6.0.3 on 2026-05-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('Samarqand', 'Samarqand'), ('Namangan', 'Namangan'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Xorazm', 'Xorazm'), ('Boshqa', 'Boshqa')], default='Toshkent', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('stir', models.CharField(blank=True, max_length=20, null=True, verbose_name='STIR')),
                ('category', models.CharField(choices=[('A', 'A — Premium'), ('B', 'B — Standart'), ('C', 'C — Minimal')], default='B', max_length=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Nofaol')], default='ACTIVE', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monthly_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_order', models.DateTimeField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dealers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlangan'), ('SHIPPED', "Jo'natilgan"), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Naqd'), ('CARD', 'Karta')], default='BANK', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
