# Generated by Django 6.0.3 on 2026-05-12 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_v2', '0003_clientbalance_last_payment_date_and_more'),
        ('sales_v2', '0011_customer_avg_order_value_customer_debt_status_and_more'),
        ('warehouse_v2', '0014_supplier_address_supplier_contract_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alert trigger threshold', max_digits=15),
        ),
        migrations.AddField(
            model_name='clientbalance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance_v2.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Kirim Kategoriyasi'), ('EXPENSE', 'Xarajat Kategoriyasi')], default='EXPENSE', max_length=10),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Forecasted date for payment', null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales_v2.invoice'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='source_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='warehouse_v2.purchaseorder'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Tasdiq kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], default='APPROVED', max_length=10),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], default='COMPLETED', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientbalance',
            name='overdue_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientbalance',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='internaltransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
