# Generated by Django 6.0.3 on 2026-05-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_assigned_warehouses_and_more'),
        ('common_v2', '0004_auditlog_model_name_auditlog_new_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. Layout, Database)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Guide Section',
                'verbose_name_plural': 'User Guide Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGuideContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('body_uz', models.TextField()),
                ('body_ru', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, help_text='Optional: only show to this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.erprole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='common_v2.userguidesection')),
            ],
            options={
                'verbose_name': 'User Guide Content',
                'verbose_name_plural': 'User Guide Contents',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
