# Generated by Django 6.0.3 on 2026-05-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLCDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=502)),
                ('protocol', models.CharField(choices=[('MODBUS', 'Modbus TCP'), ('OPCUA', 'OPC UA'), ('SIMULATOR', 'Sanoat Simulyatori')], default='SIMULATOR', max_length=20)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(choices=[('FLOAT', 'Float'), ('INT', 'Integer'), ('BOOL', 'Boolean')], default='FLOAT', max_length=20)),
                ('current_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='telemetry.plcdevice')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryHistorian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='telemetry.plctag')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tag', 'timestamp'], name='telemetry_t_tag_id_1144b0_idx')],
            },
        ),
    ]
