# Generated by Django 6.0.3 on 2026-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0012_alter_blockproduction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderstage',
            name='machine_status',
            field=models.CharField(choices=[('ACTIVE', 'Aktiv'), ('MAINTENANCE', 'Texnik xizmat'), ('OFFLINE', "O'f-line")], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorderstage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionorderstage',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Kunlik'), ('NIGHT', 'Tungi')], default='DAY', max_length=20),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Density error, Size error, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='is_recycleable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='qc_photos/'),
        ),
    ]
