# Generated by Django 6.0.3 on 2026-05-11 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0013_productionorderstage_machine_status_and_more'),
        ('warehouse_v2', '0013_rename_date_warehousetransfer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproduction',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockproduction',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Kunlik'), ('NIGHT', 'Tungi')], default='DAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockproduction',
            name='status',
            field=models.CharField(choices=[('COOLING', 'Sovutilmoqda'), ('READY', 'Tayyor'), ('DEFECT', 'Brak'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan')], default='COOLING', max_length=50),
        ),
        migrations.CreateModel(
            name='FinishedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=50, unique=True)),
                ('classification', models.CharField(choices=[('A_CLASS', 'A-Class (Premium)'), ('B_CLASS', 'B-Class (Standard)'), ('C_CLASS', 'C-Class (Economic)'), ('REJECT', 'Reject (Brak)')], default='B_CLASS', max_length=20)),
                ('status', models.CharField(choices=[('COOLING', 'Sovutilmoqda'), ('QC_PENDING', 'Sifat nazoratida'), ('READY', 'Sotuvga tayyor'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan'), ('RECYCLE', 'Qayta ishlashga')], default='COOLING', max_length=20)),
                ('actual_weight', models.FloatField(blank=True, null=True)),
                ('actual_density', models.FloatField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('rack', models.CharField(blank=True, max_length=50)),
                ('qr_code_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_blocks', to='production_v2.blockproduction')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse_v2.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='production_v2.finishedblock')),
            ],
        ),
    ]
