# Generated by Django 6.0.3 on 2026-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0014_blockproduction_operator_blockproduction_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedblock',
            name='height',
            field=models.FloatField(blank=True, help_text='mm', null=True),
        ),
        migrations.AddField(
            model_name='finishedblock',
            name='length',
            field=models.FloatField(blank=True, help_text='mm', null=True),
        ),
        migrations.AddField(
            model_name='finishedblock',
            name='moisture',
            field=models.FloatField(blank=True, help_text='%', null=True),
        ),
        migrations.AddField(
            model_name='finishedblock',
            name='visual_defects',
            field=models.TextField(blank=True, help_text='Visual defects description or tags'),
        ),
        migrations.AddField(
            model_name='finishedblock',
            name='width',
            field=models.FloatField(blank=True, help_text='mm', null=True),
        ),
    ]
