# Generated by Django 6.0.3 on 2026-05-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_v2', '0015_finishedblock_height_finishedblock_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedblock',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Yaratildi'), ('COOLING', 'Sovutilmoqda'), ('QC_PENDING', 'Sifat nazoratida'), ('READY', 'Sotuvga tayyor'), ('TRANSFERRED', 'O‘tkazildi'), ('CUTTING', 'Kesish jarayonida'), ('FINISHING', 'Pardozlash jarayonida'), ('PACKAGED', 'Qadoqlandi'), ('SHIPPED', 'Jo‘natildi'), ('RESERVED', 'Band qilingan'), ('SOLD', 'Sotilgan'), ('RECYCLE', 'Qayta ishlashga')], default='COOLING', max_length=20),
        ),
    ]
