# Generated by Django 6.0.3 on 2026-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='attachment',
            field=models.FileField(blank=True, help_text='Tasdiqlovchi hujjat (PDF, rasm)', null=True, upload_to='accounting/attachments/'),
        ),
    ]
