# Generated by Django 6.0.3 on 2026-05-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Davlat raqami')),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Yuk mashinasi'), ('VAN', 'Mikroavtobus'), ('CAR', 'Avtomobil'), ('LOADER', "Yuk ko'taruvchi")], default='TRUCK', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Yuk ko'tarish qobiliyati (kg)")),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('MAINTENANCE', "Ta'mirda"), ('INACTIVE', 'Nofaol')], default='ACTIVE', max_length=15)),
                ('mileage_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
